version: "3.7"

services:
    database: 
        image: mysql:5.7
        container_name: database
        environment:
            MYSQL_ROOT_PASSWORD: talha123
            MYSQL_DATABASE: bookstore_db
            MYSQL_USER: clarusway
            MYSQL_PASSWORD: Clarusway_1
        networks:
            - bookstorenet

    webapp:
        image: bookstore-api:latest 
        container_name: mybookstoreapp
        restart: always
        depends_on:
            - database
        ports:
            - "80:80"
        networks:
            - bookstorenet

networks:
    bookstorenet:
        driver: bridge
                   